{% set python_min = '3.10' %}
{% set name = "etspy" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/etspy-{{ version }}.tar.gz
  sha256: b29a782a1f45da2af43d5a086a0ff7ea2b3cff8849b045d86aefa0d9b0da6c0e

build:
  number: 1

outputs:
  - name: etspy
    build:
      noarch: python
    script: install.sh
    requirements:
      host:
        - python {{ python_min }}
        - poetry-core
        - pip
      run:
        - python >={{ python_min }},<3.13
        - pystackreg >=0.2.8,<0.3.0
        - astra-toolbox >=2.1.0,<3.0.0
        - hyperspy >=2.1.1,<3.0.0
        - hyperspy-gui-ipywidgets >=2.0.2,<3.0.0
        - numba >=0.60.0,<0.61.0
        - typing_extensions >=4.12.2,<5.0.0
        - numpy >=1.26.0,<3.0.0
        - h5py >=3.12.1,<4.0.0
        - ffmpeg
      run_constrained:
        - ipykernel >=6.29.5,<7.0.0
        - cupy >=13.3.0,<14.0.0
    test:
      imports:
        - etspy
        - etspy.api
      commands:
        - pip check
      requires:
        - pip
  - name: etspy-gpu
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage('etspy', exact=True) }}
        - cupy >=13.3.0,<14.0.0
    test:
      imports:
        - etspy
        - etspy.api
        - cupy
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://pages.nist.gov/etspy/
  summary: Suite of tools for processing and reconstruction of electron tomography data
  dev_url: https://github.com/usnistgov/etspy
  license: NIST-PD-fallback
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jat255
    - AndrewHerzing
